# config.yaml: Global configuration for the Spanish corpus scraping framework

# --- Polite Scraping Settings ---
# Defines the behavior of the network-facing Scraper component.
politeness:
  # Base delay in seconds between consecutive requests to the same domain.
  request_delay: 1.0
  # Random jitter to add to the delay (e.g., a value of 1.0 adds a random delay between 0 and 1 seconds).
  jitter: 0.5
  # Request timeout in seconds.
  timeout: 45
  # Number of retry attempts for failed requests (e.g., timeouts, 5xx errors).
  retry_attempts: 2
  # SSL certificate verification - set to false for sites with certificate issues
  ssl_verify: false

# --- Extraction Engine Settings ---
# Configures the text extraction strategy.
extraction:
  # Primary engine for main content extraction.
  primary_engine: 'trafilatura'
  # Fallback engine for cases where the primary fails or for site-specific rules.
  fallback_engine: 'beautifulsoup'
  # Headless browser engine for JavaScript-heavy sites.
  headless_engine: 'playwright'
  # Link following settings for discovering new content
  follow_links: true
  # Maximum links to extract per page
  max_links_per_page: 50
  # Maximum depth for link following (to prevent infinite loops)
  max_link_depth: 2

# --- Validation and Quality Control ---
# Rules to ensure the quality of the extracted text.
validation:
  # Minimum number of words required for a document to be saved.
  min_word_count: 50
  # Optional: Minimum number of sentences required. Set to 0 to disable.
  min_sentence_count: 2
  # ISO 639-1 code for the required language. Documents in other languages will be skipped.
  required_language: 'es'
  # Confidence threshold (0.0 to 1.0) for the language detection model.
  lang_detect_confidence: 0.25

# --- Storage and Persistence Settings ---
# Defines where and how data is stored.
storage:
  # Root directory for all output.
  output_dir: '../data/corpus_raw'
  # Directory for log files.
  log_dir: '../data/logs'
  # Directory for state management files (e.g., checkpoint database).
  state_dir: '../data/state'
  # If true, saves the raw HTML of each processed page for debugging.
  save_raw_html: false
  # Directory to store raw HTML if save_raw_html is true.
  raw_html_dir: '../data/html_raw'

# --- Concurrency Settings ---
# Configures multithreading for faster scraping.
concurrency:
  # Number of worker threads to use for fetching and processing URLs.
  # A value of 1 disables multithreading.
  num_threads: 8